language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      cache: apt
      dist: xenial

    - os: osx
      compiler: clang

env:
  global:
    - BUILD_NAME="Ubertooth-$TRAVIS_OS_NAME-`date --iso-8601`-$TRAVIS_COMMIT"
    - ARTEFACT_BASE=$TRAVIS_BUILD_DIR/artefacts/
    - ARTEFACT_PATH=$ARTEFACT_BASE/$BUILD_NAME

addons:
  apt:
    packages:
      - libbluetooth-dev
      - libusb-1.0-0-dev
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      - libstdc++-arm-none-eabi-newlib

  homebrew:
    taps: PX4/homebrew-px4
    packages:
       - gcc-arm-none-eabi

before_script:
  # build and install latest libbtbb
  - git clone https://github.com/greatscottgadgets/libbtbb.git
  - mkdir libbtbb/build
  - cd libbtbb/build
  - cmake ..
  - make
  - sudo make install
  - export CFLAGS="-Wall -Wextra -Werror -Wno-zero-length-array"

script:
  # Host code
  - mkdir $TRAVIS_BUILD_DIR/host/build
  - cd $TRAVIS_BUILD_DIR/host/build
  - cmake ..
  - make
  - sudo make install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig; fi
  # Firmware
  - cd $TRAVIS_BUILD_DIR/firmware
  # RX only firmware
  - mkdir rx_only
  - DISABLE_TX=1 make bluetooth_rxtx
  - mv bluetooth_rxtx/bluetooth_rxtx.bin rx_only/bluetooth_rx_only.bin
  - mv bluetooth_rxtx/bluetooth_rxtx.dfu rx_only/bluetooth_rx_only.dfu
  # Regular firmware
  - make clean
  - make bluetooth_rxtx
  # Bootloader firmware
  - cd bootloader
  - make

after_success:
  # Construct archive for deploying to ubertooth-nightlies
  - mkdir -p $ARTEFACT_PATH/firmware-bin/
  - cd $TRAVIS_BUILD_DIR/libbtbb/
  - git archive --format=tar --prefix=libbtbb/ HEAD | (cd $ARTEFACT_PATH && tar xf -)
  - cd $TRAVIS_BUILD_DIR/
  - git archive --format=tar HEAD | (cd $ARTEFACT_PATH && tar xf -)
  - cp $TRAVIS_BUILD_DIR/firmware/rx_only/bluetooth_rx_only.bin $ARTEFACT_PATH/firmware-bin/
  - cp $TRAVIS_BUILD_DIR/firmware/rx_only/bluetooth_rx_only.dfu $ARTEFACT_PATH/firmware-bin/
  - cp $TRAVIS_BUILD_DIR/firmware/bluetooth_rxtx/bluetooth.bin $ARTEFACT_PATH/firmware-bin/
  - cp $TRAVIS_BUILD_DIR/firmware/bluetooth_rxtx/bluetooth.dfu $ARTEFACT_PATH/firmware-bin/
  - cp $TRAVIS_BUILD_DIR/firmware/bootloader/bootloader.bin $ARTEFACT_PATH/firmware-bin/

deploy:
  provider: pages
  verbose: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  repo: greatscottgadgets/ubertooth-nightlies
  local-dir: $ARTEFACT_BASE
  on:
    branch: travis
